apiVersion: v1
kind: Service
metadata:
  name: grafana-np
  namespace: lgtm
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  ports:
    - name: tcp-grafana
      protocol: TCP
      port: 3000
      targetPort: grafana
      nodePort: 31501   # กำหนด NodePort (ช่วง 30000-32767)
